## Arrays and Matrices Hands-On9 points
Directions
For your Hands-On, you will be practicing your new skills with arrays and matrices! This Hands-On will be graded, so be sure you complete all requirements. The best way to become a data scientist is to practice!

Please complete the following tasks in a Jupyter Notebook file, using the numpy package:

Create a five element array using your favorite numbers named myFavorites.
Perform each of the five aggregate functions on your array.
Create a five element array containing only ones named OneArrayToRuleThemAll.
Add myFavorites and OneArrayToRuleThemAll.
Multiply every element in myFavorites by two.
Call the third element in myFavorites using indexing.
Create a four element, two-by-two matrix of numbers named TheMatrixHasYou.
Access the upper left element in TheMatrixHasYou using indexing.
Find the largest number in each row for TheMatrixHasYou.
Reshape TheMatrixHasYou into a matrix with one row and four columns.


In [1]:
import numpy as np

In [2]:
myfavoites=np.array([7,19,21,24,35])

In [3]:
myfavoites

array([ 7, 19, 21, 24, 35])

In [4]:
myfavoites.min()

7

In [6]:
myfavoites.max()

35

In [8]:
myfavoites.sum()

106

In [9]:
myfavoites.mean()

21.2

In [10]:
myfavoites.std()

8.997777503361595

In [11]:
onearraytorulethemall=np.ones(5)

In [12]:
onearraytorulethemall

array([1., 1., 1., 1., 1.])

In [13]:
myfavoites+onearraytorulethemall

array([ 8., 20., 22., 25., 36.])

In [14]:
myfavoites*2

array([14, 38, 42, 48, 70])

In [16]:
myfavoites[2]

21